import SportsEsportsOutlinedIcon from "@mui/icons-material/SportsEsportsOutlined";
import KeyboardArrowDownOutlinedIcon from "@mui/icons-material/KeyboardArrowDownOutlined";
import SportsBaseballOutlinedIcon from "@mui/icons-material/SportsBaseballOutlined";
import LegendToggleOutlinedIcon from "@mui/icons-material/LegendToggleOutlined";
import CurtainsOutlinedIcon from '@mui/icons-material/CurtainsOutlined';
import LiveTvOutlinedIcon from '@mui/icons-material/LiveTvOutlined';
import StarBorderPurple500OutlinedIcon from '@mui/icons-material/StarBorderPurple500Outlined';
import MoreHorizOutlinedIcon from '@mui/icons-material/MoreHorizOutlined';

export const topicsItems = [
  {
    id: 0,
    icon1: <SportsEsportsOutlinedIcon />,
    icon2: <KeyboardArrowDownOutlinedIcon />,
    label: "Gaming",
    links: [
      "VAlheim",
      "Genshin Impact",
      "Minecraft",
      "Pokimane",
      "Halo Infinite",
      "Call Of Duty: Warzone ",
      "Path of Exile",
      "Hollow Knight: Silksong",
      "Escape from Tarkov",
      "Watch Dogs: Legion ",
    ],
  },
  {
    id: 1,
    icon1: <SportsBaseballOutlinedIcon />,
    icon2: <KeyboardArrowDownOutlinedIcon />,
    label: "Sports",
    links: [
      "NFL ",
      "NBA",
      "Megan Andreson",
      "Atlanta Hawks",
      "Los Angeles Lakers",
      "Boston Celtics ",
      "Arsenal F.C.",
      "Philadelphia 76ers",
      "Premier League",
      "UFC ",
    ],
  },
  {
    id: 2,
    icon1: <LegendToggleOutlinedIcon />,
    icon2: <KeyboardArrowDownOutlinedIcon />,
    label: "Business, Economics, and Finance",
    links: [
      "GameStop ",
      "Moderna",
      "Pfizer",
      "Johnson & Johnson",
      "AstraZeneca",
      "Walgreens ",
      "Best Buy ",
      "Novavax",
      "SpaceX",
      "Tesla",
    ],
  },
  {
    id: 3,
    icon1: <CurtainsOutlinedIcon />,
    icon2: <KeyboardArrowDownOutlinedIcon />,
    label: "Crypto",
    links: [
      "Cardano ",
      "Dogencoin",
      "Algorand",
      "Bitcoin",
      "Litecoin",
      "Basic Attention Token",
      "Bitcoin Cash  ",
      
    ],
  },
  {
    id: 4,
    icon1: <LiveTvOutlinedIcon />,
    icon2: <KeyboardArrowDownOutlinedIcon />,
    label: "Television",
    links: [
      "The Real Houswifes Of Atlanta",
      "The Bachelor",
      "Sister Wifes",
      "90 Day Fiance ",
      "Wife Swap",
      "The Amazing Race Australia  ",
      "Married at First Sight ",
      "The Real Houswives of Dallas",
      "My 600-lb Life",
      "Last Week Tonight With John Oliver",
    ],
  },
  {
    id: 5,
    icon1: <StarBorderPurple500OutlinedIcon />,
    icon2: <KeyboardArrowDownOutlinedIcon />,
    label: "Celebrity",
    links: [
      "Kim Kardashian ",
      "Doja Cat",
      "Iggy Azela",
      "Anya Taylor-Joy ",
      "Jamie Lee Curtis ",
      "Natalie Portman",
      "Henry Cavill",
      "Millie Bobby Brown ",
      "Tom Hiddleston",
      "Keanu Reeves",
    ],
  },
  {
    id: 6,
    icon1: <MoreHorizOutlinedIcon />,
    icon2: <KeyboardArrowDownOutlinedIcon />,
    label: "More Topics ",
    links: [
      "Animals And Pets",
      "Anime",
      "Art",
      "Cars and Motors Vehicles ",
      "Crafts and DIY",
      "Culture, Race, and Ethinicity",
      "Ethics and Philosophy",
      "Fashion",
      "Food and Drink",
      "History",
      "Hobbies",
      "Law",
      "Learning and Education",
      "Military",
      "Movies",
      "Music",
      "Place",
      "Podcasts and Streamers",
      "Politics",
      "Programming",
      "Reading, Writing, and Listening",
      "Religion and Spirituality",
      "Science",
      "Tabletop Games",
      "Technology",
      "Travel",
    ],
  },
];
